/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBEMOTIONS_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBEMOTIONS_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * ergoCubEmotions_IDL
 * IDL Interface to ergoCub Emotion Handler services.
 */
class ergoCubEmotions_IDL :
        public yarp::os::Wire
{
public:
    // Constructor
    ergoCubEmotions_IDL();

    /**
     * Display a specific facial expression.
     * @param command is the name of the emotion that will be set.
     * @return true/false on success/failure.
     */
    virtual bool setEmotion(const std::string& command);

    /**
     * Print the list of all the available facial expressions.
     * @return a list of commands.
     */
    virtual std::vector<std::string> availableEmotions();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBEMOTIONS_IDL_H
