site_name: ergoCub Software
site_url: https://icub-tech-iit.github.io/ergocub-software
site_description: All the software running on ergoCub
site_author: iCub-Tech
copyright: BSD 3-Clause License

repo_name: icub-tech-iit/ergocub-software
repo_url: https://github.com/icub-tech-iit/ergocub-software
edit_uri: 'edit/gh-pages/mkdocs/docs'

markdown_extensions:
  - attr_list
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "100%"

theme:
  name: material
  favicon: assets/head-solid.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: material/robot

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
    # - News:
    #     - Latest: 'latest_news.md'
    # - Install: 'install.md'
    - Documentation: https://icub-tech-iit.github.io/ergocub-software/doxygen/doc/html/index.html
    - Modules:
          - ergoCubEmotions: 'ergoCubEmotions.md'
    #     - Getting started: 'tutorial_intro.md'
    #     - How to manage a skeleton object: 'create_new_skeleton.md'
    #     - How to replay an experiment: 'replay_an_experiment.md'
    #     - How to run the pipeline in a disembodied manner: 'disembodied.md'
    #     - How to temporally align two signals: 'align_signals.md'
    #     - How to run the rehabilitation demos: 'main_apps.md'
    #     - How to run the virtual demo: 'virtual_demo.md'
    #     - How to detect the TUG lines: 'tug_lines.md'
    #     - How to run the TUG demo: 'tug_demo.md'
    #     - How to use the gazebo plugin: 'gazebo_plugin.md'
    #     - How to configure the wifi button: 'wifi_button.md'
    # - Milestones:
    #     - Y1M5: 'Y1M5.md'
    #     - Y1Q3: 'Y1Q3.md'
    #     - Comparison between Y1Q3 and Y1M5: 'comparison_releases.md'
    #     - TUG: 'TUG.md'
    # - About: 'about.md'
    # - License: 'license.md'